// <auto-generated />
namespace McLittle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tyas20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tyas20));
        
        string IMigrationMetadata.Id
        {
            get { return "201806201108270_Tyas2.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
