//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int discountId { get; set; }
        public string title { get; set; }
        public long EAN { get; set; }
        public double price { get; set; }
        public System.DateTime validUntil { get; set; }
    }
}
