//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiUpdater
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int productId { get; set; }
        public long EAN { get; set; }
        public string title { get; set; }
        public string brand { get; set; }
        public string shortDesc { get; set; }
        public string fullDesc { get; set; }
        public string imageLink { get; set; }
        public string weight { get; set; }
        public float price { get; set; }
        public string category { get; set; }
        public string subCategory { get; set; }
        public string subsubCategory { get; set; }
    }
}
